---
- include_vars: ../../vars_main.yml

- name: Crear grupos en netbox
  netbox.netbox.netbox_site_group:
    netbox_url: "{{ nb_url }}"
    netbox_token: "{{ nb_token }}"
    data:
      name: "{{ item }}"
    state: present
  with_items:
    - Branch
    - Corporate
