---
- include_vars: ../../vars_main.yml

- name: Creando regiones
  netbox.netbox.netbox_region:
    netbox_url: "{{ nb_url }}"
    netbox_token: "{{ nb_token }}"
    data:
      parent_region:
      name: Buenos_Aires
      slug: bs_as
      description: "Buenos Aires"
    state: present
